import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "./(components)/header";
import Footer from './(components)/footer';
import { createClient } from "./(auth)/client";

const notoSansJP = Noto_Sans_JP({
  weight: ["400", "500", "700", "900"],
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const { data: { user }} = await supabase.auth.getUser();
  const isLoggedIN = !!user;

  return (
    <html lang="ja">
      <body className={`${notoSansJP.className} antialiased flex flex-col`}      >
        <div className="min-h-screen flex flex-col justify-start">
          <Header loginState={false} />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
